### PR TITLE
Fix StackOverflowError on ARM

### PR DESCRIPTION
**Pull request by w4123**
Tested on an ARM AVD
https://github.com/termux/termux-packages/issues/7214#issuecomment-905750342

### CODE REVIEW

**Comment by ghost** [comment]
Thanks

**Comment by agnostic-apollo** [comment]
Probably would be better to create a patch file with `#ifdef __TERMUX__` like done in https://github.com/termux/termux-packages/blob/master/packages/openjdk-17/android11.patch directly in `termux-packages`

Edit: Already merged...

**Comment by w4123** [comment]
It seems that this is not really a Termux-specific issue. The issue is also present in upstream OpenJDK as the original code simply doesn't work with clang. (Maybe I should PR too)

**Comment by ghost** [comment]
I will convert this to patch since any changes are preferred to be stored with package build script.

**Comment by agnostic-apollo** [comment]
The plan was that in future we may directly use upstream instead of this fork, so would be better to keep all changes in one place. The `#ifdef __TERMUX__` was just an example, the `clang`/`llvm` is fine.

> (Maybe I should PR too)

That would be even better.

**Pull request merged**
